name = "note-block-api"
main = "src/index.ts"
compatibility_date = "2024-10-17"
account_id = "4aa839773109421527f1f0147e3557c0"
compatibility_flags = [ "nodejs_compat" ]

[env.local.vars]
minify = true