name: "Install"
description: "Setup Bun and install dependencies"

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.1.31

    - name: Cache node_modules
      id: cache-bun
      uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-build-${{ env.cache-name }}\
          -${{ hashFiles('**/bun.lockb') }}
        restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Install dependencies
      shell: bash
      run: bun install
# name: "Install"
# description: "Setup Bun and install dependencies"
# runs:
#   using: "composite"
#   steps:
#     - name: Setup Bun
#       uses: oven-sh/setup-bun@v2
#       with:
#         bun-version: 1.1.30
#     - name: Cache node_modules
#       uses: actions/cache@v4
#       with:
#         path: ~/.bun/install/cache
